### ISSUE TITLE
Folding help

### ISSUE THREAD

**Issue by ghost** [jjaderberg/vim-ft-asciidoc#7]
At the risk of burdening you with my problems: is there something I need to do to enable folding? In an asciidoc file, the various fold-close commands all generate an E490 No Fold Found error.  Trying to create a fold myself with `zf` generates a "cannot create fold with current foldmethod", of course. TBH, folding and I have always had a rocky relationship; it never seems to work properly for me, so it may not be vim-ft-asciidoc.  Any pointers to what I might need to do to enable folding would be appreciated, and might help other unfortunates.

**Comment by jjaderberg** [comment]
@serussell If you are still using vim-ft-asciidoc and having trouble with folding, you could check with `:verbose set foldmethod?` which foldmethod is used and wherefrom it is last set. This command should tell you that `foldmethod=expr` and that it was last set from `<somewhere>/vim-ft-asciidoc/ftplugin/asciidoc.vim`.
If it does, then you can check with `:verbose set foldexpr?` which fold expression is used and wherefrom it is last set. This hould tell you that `foldexpr=asciidoc#folding#foldexpr(v:lnum)` and that it was last set from the same location as the foldmethod.
If either of the above do not show the expected value and location from which the value was last set then they will at the same time tell you from which location the value set by this plugin is overridden.
If both of these values are set as expected, please provide an example AsciiDoc snippet for which folding does not work.

**Comment by jjaderberg** [comment]
Closing. If you get around to trying my suggestions above and the results indicate that there is a problem with this plugin I'd appreciate it if your results in a comment here. Cheers.

**Comment by ghost** [comment]
In the process of moving everything over to vim 8 packages, I cleaned up a bunch of redundant asciidoc vim files, and lo!  Verily, it fixedth everything.  Folds now work, so the issue was years of cruft.
